import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Next.js Landing Page',
  description: 'Simple landing page built with Next.js',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <header className="header">
          <div className="container">
            <h1>My Next.js App</h1>
            <nav>
              <Link href="/#about">About</Link>
              <Link href="/#services">Services</Link>
              <Link href="/#contact">Contact</Link>
            </nav>
          </div>
        </header>

        <main>{children}</main>

        <footer className="footer">
          <p>© 2025 My Next.js App. All rights reserved.</p>
        </footer>
      </body>
    </html>
  )
}

// ORIGINAL (DEFAULT)
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
